version: "3.9"

services:
  database:
    container_name: evil-licenses-db
    build: .
    image: evil-licenses-db:0.1
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: evil-licenses
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
    restart: unless-stopped

  pgadmin:
    container_name: evil-liceneses-pgadmin
    image: dpage/pgadmin4:6.1
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5051:5050
    depends_on:
      - database


